name: VSCode CI

on:
  push:
    branches: [master, main]
    tags:
      - "v*"
  pull_request:
    branches: [master, main]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        # Lock to the version shipped with VSCode 1.43+
        node-version: ['20']

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
      - run: yarn install --frozen-lockfile
      - run: yarn lint
      - run: yarn build

  # publish the extension to marketplaces
  publish:
    # run after lint passes
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: yarn package
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: nix-ide*.vsix
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish to Open VSX Registry
        run: yarn ovsx publish *.vsix --pat ${{ secrets.OPEN_VSX_TOKEN }}
      - name: Publish to Visual Studio Marketplace
        run: yarn vsce publish -p ${{ secrets.VS_MARKETPLACE_TOKEN }}
